#!/usr/bin/env bash
if [[ $# -eq 1 ]]; then
  path=$1
else
  items=`find $HOME/.kube \( -name '*.yaml' -o -name '*.yml' \)`
  path=`echo "$items" | fzf`
fi

if [[ $path == "" ]]; then
  echo "Nothing to do!"
  exit
fi

session=`basename $path`
cp -rf $HOME/.kube/$session $HOME/.kube/config
echo "Switched kubernetes context to $session"
